[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
httparse = "1.8.0"
thiserror = "1.0.37"
tokio = { version = "1.22.0", features = ["full"] }
